[build]
  publish = "."
  command = "# no build step"
  functions = "netlify/functions"

[dev]
  publish = "."
  targetPort = 0

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
